### ISSUE TITLE
Header Include Path Issue

### ISSUE THREAD

**Issue by tylerpayne** [rlidwka/node-fann#16]
I am receiving the following error after calling $ npm install fann

> fann@0.2.3 install /Users/tylerpayne/Desktop/Node/node_modules/fann
> node-gyp rebuild

  CXX(target) Release/obj.target/fann/src/fann-accs.o
In file included from ../src/fann-accs.cc:7:
In file included from ../src/node-fann.h:5:
../src/node-futil.h:7:10: fatal error: 'doublefann.h' file not found
# include <doublefann.h>

```
     ^
```

1 error generated.
make: **\* [Release/obj.target/fann/src/fann-accs.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tylerpayne/Desktop/Node/node_modules/fann
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! fann@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fann@0.2.3 install script.
npm ERR! This is most likely a problem with the fann package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fann
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--save" "fann"
npm ERR! cwd /Users/tylerpayne/Desktop/Node
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

I have FANN 2.2.0 and pkg-config and glib2 installed. I think I just need help including /usr/local/include in the GCC header search paths but have had no luck yet.

**Comment by yungookim** [comment]
I am having the same issue
```
make: *** [Release/obj.target/fann/src/fann-accs.o] Error 1
make: Leaving directory `~/a/kiwi-brain/node_modules/fann/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/a/kiwi-brain/node_modules/fann
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "fann"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! fann@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fann@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fann package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fann
npm ERR! There is likely additional logging output above.

```

**Comment by spyridon-amp** [comment]
It's bee too long since the last post here, but did anyone have any luck with this? 
I'm getting a similar error.

**Comment by krystianity** [comment]
+1

**Comment by krystianity** [comment]
forked myself through a few repos... https://github.com/krystianity/node-fann this is working for me
